apiVersion: v1
kind: ReplicationCotroller
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/lubia
        ports:
        - containerPort: 8080